### PR TITLE
Feat/multicall

### PR DESCRIPTION
**Pull request by micksabox**
# Multi-call
- `TransactionQueue.tsx` React component to display transactions from `TransactionQueueContext.tsx`
- Txs in queue can be executed in a single invoke using multi-call (account abstraction feature in Starknet)
- Displays multi-call tx status with all sub-transactions included in list
- Txs can be queued from anywhere in the game using `useTransactionQueue` React hook
- a toast is displayed for an enqueued transaction using the [`react-hot-toast`](https://react-hot-toast.com) package

Multi-call game operations included in this PR:
- Approve all game actions (trigger in Account panel for now)
- Harvest resources for a Realm
- Build a building in a Realm

## Notes

1. It would have been nice to be able to simulate the transactions in queue and see if the resulting execution would produce an error. I tried to do this [here](https://github.com/BibliothecaForAdventurers/realms-react/commit/f282242d5dc27b49a10a368e7759a5170a65d327) thinking that `estimateFee` could be used for this (it can't). `estimateFee` requires a signature, so for that reason it can only be done in the wallet itself for now. It would have been useful to return the error from the execution result and use that as a clean API to do other things. Ex. `build` fails because the wallet doesn't have enough resources? Then suggest to user to buy those resources. For now the estimateFee might fail in the wallet. As of [Argent-x v4.2.0](https://github.com/argentlabs/argent-x/releases/tag/v4.2.0) these estimate fee errors are shown to user so that might help a bit.
2. A simple convention I used for enqueuing transactions can be seen in [this](https://github.com/BibliothecaForAdventurers/realms-react/commit/5bd04d15c186efffb367fa5d3924ea3caa83fdaf) commit. Essentially it is to:
- Export a `BuildCall` object with keys as the entry point names and functions that return the call as the values
- Use `ModuleAddr` to refer to Contract addresses in a consistent and DRY manner
- The result of `BuildCall.method(args)` should also contain the metadata used to display the tx in lists. By convention the args to the BuildCall are always passed in as metadata so no duplication at call site is needed. Using this pattern it is easy to then define the display for each tx in the list, whether it is an individual tx or a multi-call. 
3. The transactions are enqueued using the `RawCallData` type, which is not struct-aware. Ex: a Uint256 will need to be converted from a BN into two structs. For this I made the helper [`rawCalldata.ts`](https://github.com/BibliothecaForAdventurers/realms-react/commit/a16417cbd4da7731960d8ca537497f7793f34c5a). It's not ideal to use RawCallData as noted [here](https://github.com/apibara/starknet-react/issues/102#issuecomment-1117300248). The ABI of the tx is currently not used but it would be necessary to create a generic helper which can convert down to RawCallData.

Screen Shot 2022-07-03 at 1 35 35 AM

### CODE REVIEW

**Comment by micksabox** [comment]
Fixed an error with the build, ready to be reviewed and lgtm

**Review by RedBeardEth — CHANGES_REQUESTED** [review]
image

Tx Metadata didn't want to show for me for approvals (buildings working fine)

image
Individual remove transaction buttons would be good (if a large queue is quite annoying if you accidentally click the wrong button - I also find the CTA "Sign for 3 commands" to get a little lost - maybe a brighter button at the bottom of the list (similar to general ecommerce minicart) would be better 

This is looking really good!

**Comment by micksabox** [comment]
- Fixed bug with approve multi call display in list
- Added the ability to remove items from queue.
- Made the primary button wider, and with different colour variant. I think the top is a fine spot, eliminates the need to scan visually to bottom of screen.

Screen Shot 2022-07-12 at 6 13 17 PM

**Comment by RedBeardEth** [comment]
LGTM!

**Pull request merged**
