### PR TITLE
AMM polish #199

### PR DESCRIPTION
**Pull request by r0man1337**
1. Added 7-day mini-charts to the resource emporium
2. $LORDS spelling unification (LORDS replaced with $LORDS, added LORDS icon next to the numbers)
3. Swap: The section with buttons and total counts is now fixed at the bottom
4. LP transactions added to the queue system
5. Added price impact placeholder

### CODE REVIEW

**Comment by ponderingdemocritus** [comment]
Minor features to add:

- [ ] Add Resource Icons and the quantity being purchased into Tx metadata to jazz up the tx cart.
- [ ] Add in time period for the graph in the top row header so people know the context of the graph (is it 7 days?)
- [ ] Adjust the quick add buttons (These were just temp added in. Some other display method would be better, like a drop down which exposes them, but they are not always there.)

**Comment by ponderingdemocritus** [comment]
everything else looks great!

**Comment by ponderingdemocritus** [comment]
Screenshot from 2022-09-28 15-52-07

- [ ] Padding in LP section

**Comment by RedBeardEth** [comment]
Looking good! Are we able to display rates when no Web3 connection (currently staying at 0 as below)
image

**Comment by r0man1337** [comment]
@ponderingdemocritus pushed new commits with updates:

1. Approve tokens buttons styling update (now they are standing in a row on pc)
2. Added "Clear" button to the swap resources sidebar
3. 7d chart moved to separate column
4. Resources and its amount is now displaying in the tx queue
5. New feature: set max amount to input when clicking on resource balance
6. Quick add costs moved to popovers
7. Fixed paddings in LP section
8. Switch buttons restyling to similar to the main ui.

**Comment by ponderingdemocritus** [comment]
LGTM! @RedBeardEth any comments?

**Pull request merged**
