### PR TITLE
Feat/storybook monorepo

### PR DESCRIPTION
**Pull request by micksabox**
- Storybook configured at root of monorepo
- This PR focuses on storybook support and fixing failing stories to be in separate PR
- Added Realms word mark in Storybook theme

# Issues
- Duplicated `tailwind.config.js` at root and within `apps/atlas`. Tried setting up a [custom configuration via PostCSS](https://tailwindcss.com/docs/configuration#using-a-different-file-name) but storybook doesn't pick it up when going in the direction of root -> atlas. Neither does this work when specifying the root `tailwind.config.js` from the atlas. For now having 2 tailwind.config.js works but obviously it's not ideal to have 2 files.

### CODE REVIEW

**Comment by ponderingdemocritus** [comment]
This looks good for a merge since it's all storybook - can you fix conflicts and propose non-draft

**Comment by ponderingdemocritus** [comment]
Is this ready to merge? Can we clear this

**Comment by micksabox** [comment]
Leaving this link here to fix the multiple tailwind config js files, we can opt to fix in separate PR.

https://blog.nrwl.io/setup-next-js-to-use-tailwind-with-nx-849b7e21d8d0

**Comment by micksabox** [comment]
Quick update: The version of React moved up and is incompatible with Storybook last I checked, need to check again later

**Pull request closed without merging**
