### PR TITLE
New UI features #203

### PR DESCRIPTION
**Pull request by r0man1337**
PR related to #203 

Done:
1. Added Crown icon next to Realms name if you dont own it.
2. Realm Lord address appeared in tooltip on crown hover
3. Added Tooltip component wrapper
4. Details button renamed to More actions (Realm card)
5. Added LORDS icon everywhere where LORDS appears
6. Added Clear Filters button to Filter bar at Realms page.

UPD: 7. Added quick switch feature #210

### CODE REVIEW

**Comment by r0man1337** [comment]
7. Added quick switch feature https://github.com/BibliothecaForAdventurers/realms-react/issues/210

**Comment by r0man1337** [comment]
found update bug, fixing

**Comment by ponderingdemocritus** [comment]
Did the navigation break? I cannot nav between pages

**Comment by r0man1337** [comment]
> Did the navigation break? I cannot nav between pages

Ye, I mentioned that in the last comment. Noticed before going to sleep yesterday. Now its fixed, should work fine. Also fixed second bug with realms info update when switching pages (wrong loop key).

**Pull request closed without merging**
