### PR TITLE
fix(realms): recalculate gradients order of refl

### PR DESCRIPTION
**Pull request by rvorias**
This repositions all realms of the Order of Reflection such that their direction aligns with the continent and sea, except for realm 4154 because BannersCaygeon has written some cool lore for it.

Before merging I need to update mapbox as well.

### CODE REVIEW

**Comment by ponderingdemocritus** [comment]
Has mapbox been updated on this branch?

**Comment by rvorias** [comment]
> 

No, will do after merge!

**Comment by rvorias** [comment]
@ponderingdemocritus could you review perchance?

**Review by ponderingdemocritus — APPROVED** [review]

**Comment by rvorias** [comment]
Thanks!

**Pull request merged**
